# work
name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        b: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        c: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        d: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        e: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    name: ${{ matrix.a }}${{ matrix.b }}${{ matrix.c }}${{ matrix.d }}${{ matrix.e }}
    steps:
      - run: ls
